repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
#  - repo: https://github.com/gitguardian/ggshield
#    rev: v1.10.8
#    hooks:
#      - id: ggshield
#        language_version: python3
#        stages: [commit]
